name: Go-Build-Test-Sonar

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]  

jobs:

  build:
    name: BuildTestSonar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -coverprofile=cover.out

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        SONAR_ORGANIZATION: "diegosmorf"     
      with:
        args: >
          -Dsonar.organization= "diegosmorf"
          -Dsonar.login="${{ secrets.SONAR_TOKEN }}" 
          -Dsonar.host.url="https://sonarcloud.io" 
          -Dsonar.projectKey="diegosmorf_rpg-combat-dojo-golang"
          -Dsonar.go.coverage.reportPaths=coverage.out       
          -Dsonar.go.tests.reportPaths=test.out
          -Dsonar.verbose=true
