name: Go-Build-Test-Sonar

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]  

jobs:

  build:
    name: Go-Build-Test-Sonar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:      
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test ./... -coverprofile=cover.out

    - name: SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
      with:
        args: >                    
          -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.go.coverage.reportPaths=cover.out       
          -Dsonar.go.tests.reportPaths=test.out
          -Dsonar.verbose=true
