name: Go-Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]  

jobs:

  build:
    name: BuildTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -coverprofile=cover.out

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          args: 
            -Dsonar.organization=${{PROJECT_KEY}}
            -Dsonar.projectKey=${{PROJECT_KEY}}
            -Dsonar.python.coverage.reportPaths=coverage.xml         
